---
title: Tramites de Naturalización
author: ''
date: '2018-12-13'
slug: tramites-de-naturalización
categories:
  - POLITICA MIGRATORIA
tags:
  - NATURALIZACION
  - ESTADISTICAS
  - POLITICA MIGRATORIA
  - REGULARIZACION
description: "Datos sobre los tramites de naturalización que se llevan a cabo ante la DNM.."
---
#TRAMITES DE NATURALIZACION

* Los **datos estadísticos desmienten los argumentos** esgrimidos por el Poder Ejecutivo en el DNU 70/2017 **para modificar la Ley 346 de Ciudadanía y Naturalización** bajo el pretexto de haber “advertido otra modalidad de fraude a la Ley Migratoria que hace indispensable modificar la Ley N° 346 de Ciudadanía, **a fin de precisar que es requisito tener residencia permanente o temporaria de forma continua en los DOS (2) años anteriores,** a los efectos del cómputo del arraigo necesario para acceder a la nacionalidad por naturalización” (DNU 70/2017).

* Según la Cámara Nacional Electoral, entre 2000 y 2015 se registraron 61.940 Cartas de Ciudadanía otorgadas, con un **aumento pronunciado en 2006/2007, momento a partir del cual las cifras se mantienen relativamente estables. Dicho aumento coincide con los programas de regularización** documentaria migratoria para ciudadanos de países extra-Mercosur y "Patria Grande". La mayor cantidad de naturalizaciones corresponde a personas peruanas, bolivianas y paraguayas (únicas nacionalidades con más de 5000 trámites de naturalización registrados), es decir, **personas con altas posibilidades de regularizar su situación migratoria o de obtener permiso de residencia. Esto demuestra que no hay fraude a la Ley de Migraciones**^[ Fuente: Datos solicitados a la Cámara Nacional Electoral por la Dra. Corina Courtis (UBA/CONICET).].

